### PR TITLE
Re-sync with internal repository

### PR DESCRIPTION
**Pull request by xubonnie**
The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.

### CODE REVIEW

**Comment by tehnerd** [comment]
JFYI: that broke open source Travis build

**Comment by udippant** [comment]
This commit replaced the existing travis configuration. We'll need to configure the build hook via 'fbcode_builder'

**Comment by tehnerd** [comment]
Will fbcode builder build all the tools (eg grpc example etc) aside from core libraries or this would be obsoleted?

**Comment by xubonnie** [comment]
Currently trying to fix it by updating fbcode builder used (solution recommended by OSS team).

**Comment by tehnerd** [comment]
the issue is that katran also depends on libraries which are not in fbcode builder (e.g. libbpf). and this is just about katran/ directore. examples/ depends on few third party libraries as well (e.g. grpc etc)

**Pull request merged**
