### PR TITLE
Fix repository URL in .travis.yml config

### PR DESCRIPTION
**Pull request by leonardinius**
FIx accidental  private repo URL leak.
E.g. `s|https://github.com/tehnerd/katran|https://github.com/${TRAVIS_REPO_SLUG}`

### CODE REVIEW

**Comment by tehnerd** [comment]
ops ;) tnx for fixing this

**Comment by tehnerd** [comment]
will merge as soon as build will pass.

**Comment by leonardinius** [comment]
Hmmm The way `.travis.yml` currently works - I do not think the build is executed from the pull request commits, main master only.

I could help to adjust the config depending on what you want to achieve here. 

Options: 
- do not pull at all but re-use the clone travis performs automatically
- use something similar to `${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}}`
etc ..

**Comment by tehnerd** [comment]
idea was - we can build only under ubuntu 18.04. by default travis runs under 16.04 (or something like this). the only way to get 18.04 env - is to run build from docker. question is - how to get proper link to the diff (so master was initial version, just to have something. probably there are some env variables which would allow us to get a link to the diff/branch which have triggered travis to run. would appreciate any help there :) )

**Comment by leonardinius** [comment]
Understood.
 I will try to play with that in a fork. If I happen to have something to share or suggest - I will file a separate pull request.

**Comment by tehnerd** [comment]
yeah. lets start with fixing private repo first. thanks!

**Comment by tehnerd** [comment]
ok i think i have nailed it down. something like this https://github.com/tehnerd/katran/blob/master/.travis.yml should works as we want.
@leonardinius

**Pull request merged**
